import { useState } from 'react';
import { isValidApplicationId } from '../midnight/application-id.js';

interface Props {
  disabled: boolean;
  disabledReason: string | null;
  busy: boolean;
  onProve: (income: bigint, threshold: bigint, applicationId: string) => void;
}

function parseAmount(value: string): bigint {
  const digits = value.replace(/[^0-9]/g, '');
  return BigInt(digits === '' ? 0 : digits);
}

/**
 * Live Preprod proof panel: the applicant enters their exact monthly income
 * (PRIVATE witness), the required threshold (PUBLIC circuit argument) and the
 * application identifier they are claiming against (PUBLIC claim-scoping input).
 *
 * After submission the exact income and the per-claim identity are never
 * re-shown in Live mode — only the public outcome. The income is handed to the
 * witness closure directly; the fresh applicant id is generated by the proof
 * hook, never in this component.
 */
export function ProofPanel({ disabled, disabledReason, busy, onProve }: Props) {
  const [incomeInput, setIncomeInput] = useState('82500');
  const [thresholdInput, setThresholdInput] = useState('50000');
  const [applicationId, setApplicationId] = useState('loan-app-2026-01');

  const applicationIdValid = isValidApplicationId(applicationId);

  const handleProve = () => {
    if (disabled || busy || !applicationIdValid) return;
    onProve(parseAmount(incomeInput), parseAmount(thresholdInput), applicationId.trim());
  };

  return (
    <div className="card inputs">
      <label>
        <span>
          Monthly income <em>(private witness)</em>
        </span>
        <input
          inputMode="numeric"
          value={incomeInput}
          onChange={(e) => setIncomeInput(e.target.value)}
          placeholder="82500"
        />
      </label>
      <label>
        <span>
          Required threshold <em>(public circuit argument)</em>
        </span>
        <input
          inputMode="numeric"
          value={thresholdInput}
          onChange={(e) => setThresholdInput(e.target.value)}
          placeholder="50000"
        />
      </label>
      <label>
        <span>
          Application ID <em>(public claim scope)</em>
        </span>
        <input
          value={applicationId}
          onChange={(e) => setApplicationId(e.target.value)}
          placeholder="loan-app-2026-01"
        />
        <small className="hint">
          The application this claim is for. Reusing the same ID with the same
          claim identity is rejected on-chain — but each claim here uses a fresh
          identity, so independent applications are never blocked by each other.
        </small>
      </label>
      <div className="actions">
        <button
          onClick={handleProve}
          disabled={disabled || busy || !applicationIdValid}
        >
          {disabled ? 'Live proof unavailable' : busy ? 'Proving…' : 'Prove income on Preprod'}
        </button>
      </div>
      {disabledReason && <p className="note">{disabledReason}</p>}
      {!applicationIdValid && (
        <p className="note err">Enter an application ID to enable the proof.</p>
      )}
      <p className="note privacy-note">
        <strong>Privacy:</strong> your exact income and your per-claim identity
        stay in this tab — they are only ever inside the zero-knowledge witness.
        They are not displayed after submission, not stored, not logged, and
        never sent anywhere. Only the Application ID and threshold are public.
      </p>
    </div>
  );
}