import { useEffect, useRef, useState } from 'react';
import { isValidApplicationId } from '../midnight/application-id.js';

interface Props {
  disabled: boolean;
  disabledReason: string | null;
  busy: boolean;
  onProve: (income: bigint, threshold: bigint, applicationId: string) => void;
}

function parseAmount(value: string): bigint {
  const digits = value.replace(/[^0-9]/g, '');
  return BigInt(digits === '' ? 0 : digits);
}

/**
 * Live Preprod proof panel: the applicant enters their exact monthly income
 * (PRIVATE witness), the required threshold (PUBLIC circuit argument) and the
 * application identifier they are claiming against (PUBLIC claim-scoping input).
 *
 * After submission the exact income and the per-claim identity are never
 * re-shown in Live mode — only the public outcome. The income is handed to the
 * witness closure directly; the fresh applicant id is generated by the proof
 * hook, never in this component.
 */
export function ProofPanel({ disabled, disabledReason, busy, onProve }: Props) {
  const [incomeInput, setIncomeInput] = useState('82500');
  const [thresholdInput, setThresholdInput] = useState('50000');
  const [applicationId, setApplicationId] = useState('loan-app-2026-01');
  const prevBusy = useRef(false);

  // Once a Live proving run has fully completed (granted, denied, or error)
  // the exact income must no longer be visible in the panel. The value is only
  // cleared on the `busy` true → false transition — i.e. after the attempt
  // finishes — and was already read at submit time. UI-only change: nothing is
  // persisted, logged, or transmitted differently, and proving is unaffected.
  // (This deliberately clears on any finished attempt, not just `granted`,
  // because ProofPanel cannot observe the verdict without a new prop.)
  useEffect(() => {
    if (prevBusy.current && !busy) {
      setIncomeInput('');
    }
    prevBusy.current = busy;
  }, [busy]);

  const applicationIdValid = isValidApplicationId(applicationId);

  const handleProve = () => {
    if (disabled || busy || !applicationIdValid) return;
    onProve(parseAmount(incomeInput), parseAmount(thresholdInput), applicationId.trim());
  };

  return (
    <form
      className="claim-form"
      onSubmit={(e) => {
        e.preventDefault();
        handleProve();
      }}
    >
      <fieldset className="fieldset-card -private">
        <legend className="hidden">Private details</legend>
        <div className="set-head">
          <span className="set-title">
            <span className="tag -private" aria-hidden="true">
              <span className="dot" />
              Private
            </span>
            Your monthly income
          </span>
        </div>
        <p className="set-desc">
          Seen by nobody — your income only ever exists inside the zero-knowledge
          proof. It is cleared from this form after each attempt.
        </p>
        <div className="field">
          <label className="field-label" htmlFor="income">
            Monthly income
          </label>
          <input
            id="income"
            className="input"
            inputMode="numeric"
            autoComplete="off"
            spellCheck={false}
            value={incomeInput}
            onChange={(e) => setIncomeInput(e.target.value)}
            placeholder="e.g. 82500"
          />
        </div>
      </fieldset>

      <fieldset className="fieldset-card">
        <legend className="hidden">Public claim details</legend>
        <div className="set-head">
          <span className="set-title">
            <span className="tag -public" aria-hidden="true">
              <span className="dot" />
              Public
            </span>
            What the verifier sees
          </span>
        </div>
        <p className="set-desc">
          The threshold and the application id are visible to the verifier and
          recorded on-chain — by design, never the income itself.
        </p>
        <div className="field">
          <label className="field-label" htmlFor="threshold">
            Required monthly income
          </label>
          <input
            id="threshold"
            className="input"
            inputMode="numeric"
            autoComplete="off"
            spellCheck={false}
            value={thresholdInput}
            onChange={(e) => setThresholdInput(e.target.value)}
            placeholder="e.g. 50000"
          />
          <span className="field-hint">
            The threshold the verifier requires you to meet for this claim.
          </span>
        </div>
        <div className="field">
          <label className="field-label" htmlFor="applicationId">
            Application ID
          </label>
          <input
            id="applicationId"
            className="input"
            autoComplete="off"
            spellCheck={false}
            value={applicationId}
            onChange={(e) => setApplicationId(e.target.value)}
            placeholder="loan-app-2026-01"
          />
          <span className="field-hint">
            The application this claim is for. Each claim is scoped to one
            application, so a proof can&rsquo;t be reused elsewhere — re-claiming
            the same application with the same identity is rejected on-chain.
          </span>
        </div>
      </fieldset>

      <div className="actions-line">
        <button
          type="submit"
          className="btn btn-primary"
          disabled={disabled || busy || !applicationIdValid}
          aria-busy={busy}
        >
          {busy ? (
            <>
              <span className="btn-spinner" aria-hidden="true" />
              Proving…
            </>
          ) : disabled ? (
            'Live proof unavailable'
          ) : (
            'Prove privately'
          )}
        </button>
        {disabledReason && <span className="step">{disabledReason}</span>}
      </div>
      {!applicationIdValid && (
        <p className="field-err" style={{ fontSize: 13 }}>
          Enter an application ID to enable the proof.
        </p>
      )}
      <p className="privacy-note">
        <strong>Privacy:</strong> your exact income and your per-claim identity
        stay in this tab — they only ever live inside the zero-knowledge witness.
        They are not displayed after submission, not stored, not logged, and
        never sent anywhere.
      </p>
    </form>
  );
}