/**
 * Proofly — shared witness wiring.
 *
 * This is THE privacy boundary of the application. Two secrets are bound into
 * Compact WITNESS closures (the ShadowBid / ShadowPass-Level5 pattern):
 *
 *   1. `income`      — the applicant's exact monthly income;
 *   2. `applicantId` — a fresh 32-byte claim identity (`crypto.getRandomValues`,
 *                      in-memory only, regenerated once per claim).
 *
 * Both are therefore:
 *   - NEVER circuit arguments (only `requiredMonthlyIncome` and `applicationId`
 *     are public);
 *   - NEVER written to ledger state;
 *   - NEVER logged, stored, or placed in a URL.
 *
 * The secrets enter here from the React component state and flow exclusively
 * through `ctx.privateState` machinery into the zero-knowledge circuit.
 */

import type { WitnessContext } from '@midnight-ntwrk/compact-runtime';

/**
 * Public ledger shape observed by the compiled contract (and passed to witnesses
 * via their `WitnessContext`). Structurally matches the generated `Ledger` type
 * in `compiled-contract.d.ts`.
 */
export interface ProoflyLedger {
  readonly proofCount: bigint;
  usedNullifiers: {
    isEmpty(): boolean;
    size(): bigint;
    member(key: Uint8Array): boolean;
    lookup(key: Uint8Array): boolean;
    [Symbol.iterator](): Iterator<[Uint8Array, boolean]>;
  };
}

/** Structural shape the compiled Proofly `Contract` constructor requires. */
export interface ProoflyWitnesses<PS = unknown> {
  income(context: WitnessContext<ProoflyLedger, PS>): [PS, bigint];
  applicantId(context: WitnessContext<ProoflyLedger, PS>): [PS, Uint8Array];
}

/**
 * Build the `income` + `applicantId` witnesses for a single live run.
 *
 * @param income      The applicant's exact monthly income. Referenced through
 *                    this closure only — never a circuit argument.
 * @param applicantId Fresh 32-byte claim identity, generated by the caller once
 *                    per claim (`crypto.getRandomValues`) and referenced through
 *                    this closure only — never a circuit argument, never stored.
 */
export function createProoflyWitnesses<PS = unknown>(
  income: bigint,
  applicantId: Uint8Array,
): ProoflyWitnesses<PS> {
  return {
    income(context: WitnessContext<ProoflyLedger, PS>): [PS, bigint] {
      return [context.privateState, income];
    },
    applicantId(context: WitnessContext<ProoflyLedger, PS>): [PS, Uint8Array] {
      return [context.privateState, applicantId];
    },
  };
}